version: 2
updates:
  # NPM dependencies
  - package-ecosystem: "npm"
    directory: "/workers/backend"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: auto
   
  # # Docker dependencies
  # - package-ecosystem: "docker"
  #   directory: "/"
  #   schedule:
  #     interval: "weekly"
  #   open-pull-requests-limit: 10