name: ESLint + SonarCloud
on:
  pull_request:
    branches: ["main"]
  schedule:
    - cron: "30 1 * * 0"

jobs:
  analysis:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: cd workers/backend && bun i

      - name: Run ESLint
        run: bun run eslint . 
          --ext .js,.jsx,.ts,.tsx 
          --format json 
          --output-file eslint-report.json
        continue-on-error: true

      - name: Run tests with coverage
        run: bun test --coverage
        
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=leuan
            -Dsonar.projectKey=leuan_plateplan
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.javascript.eslint.reportPaths=eslint-report.json
            -Dsonar.sources=src
            -Dsonar.tests=test
            -Dsonar.analysis.resultFormat=SARIF
            -Dsonar.analysis.resultFile=sonarcloud-analysis-result.sarif

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: sonarcloud-analysis-result.sarif
          category: sonarcloud